package all

import (
	_ "github.com/aiyun/openapm/mecury/plugins/input/apache"
	_ "github.com/aiyun/openapm/mecury/plugins/input/dapper"
	_ "github.com/aiyun/openapm/mecury/plugins/input/dns_query"
	_ "github.com/aiyun/openapm/mecury/plugins/input/docker"
	_ "github.com/aiyun/openapm/mecury/plugins/input/elasticsearch"
	_ "github.com/aiyun/openapm/mecury/plugins/input/haproxy"
	_ "github.com/aiyun/openapm/mecury/plugins/input/http_response"
	_ "github.com/aiyun/openapm/mecury/plugins/input/java_metrics_http"
	_ "github.com/aiyun/openapm/mecury/plugins/input/log_collect"
	_ "github.com/aiyun/openapm/mecury/plugins/input/memcached"
	_ "github.com/aiyun/openapm/mecury/plugins/input/mongodb"
	_ "github.com/aiyun/openapm/mecury/plugins/input/mysql"
	_ "github.com/aiyun/openapm/mecury/plugins/input/net_response"
	_ "github.com/aiyun/openapm/mecury/plugins/input/nginx"
	_ "github.com/aiyun/openapm/mecury/plugins/input/ping"
	_ "github.com/aiyun/openapm/mecury/plugins/input/postgresql"
	_ "github.com/aiyun/openapm/mecury/plugins/input/redis"
	_ "github.com/aiyun/openapm/mecury/plugins/input/system"
	_ "github.com/aiyun/openapm/mecury/plugins/input/tcp_listener"
	_ "github.com/aiyun/openapm/mecury/plugins/input/udp_listener"
	_ "github.com/aiyun/openapm/mecury/plugins/input/zookeeper"
)
