// Code generated by protoc-gen-go.
// source: vgo.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	vgo.proto

It has these top-level messages:
	Group
	Users
	Alerts
	Reply
	Alert
	User
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Group struct {
	Id     string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Alerts map[string]*Alert `protobuf:"bytes,2,rep,name=alerts" json:"alerts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Users  map[string]*User  `protobuf:"bytes,3,rep,name=users" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto1.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Group) GetAlerts() map[string]*Alert {
	if m != nil {
		return m.Alerts
	}
	return nil
}

func (m *Group) GetUsers() map[string]*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Users struct {
	GroupId string           `protobuf:"bytes,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Users   map[string]*User `protobuf:"bytes,2,rep,name=users" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Users) Reset()                    { *m = Users{} }
func (m *Users) String() string            { return proto1.CompactTextString(m) }
func (*Users) ProtoMessage()               {}
func (*Users) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Users) GetUsers() map[string]*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Alerts struct {
	GroupId string            `protobuf:"bytes,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Alerts  map[string]*Alert `protobuf:"bytes,2,rep,name=alerts" json:"alerts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Alerts) Reset()                    { *m = Alerts{} }
func (m *Alerts) String() string            { return proto1.CompactTextString(m) }
func (*Alerts) ProtoMessage()               {}
func (*Alerts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Alerts) GetAlerts() map[string]*Alert {
	if m != nil {
		return m.Alerts
	}
	return nil
}

type Reply struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto1.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Alert struct {
	// 1 : average 2 : gauge 3: alive status
	Type int32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	// 1:   >,   2:  = ,   3: <
	Operator   int32  `protobuf:"varint,2,opt,name=operator" json:"operator,omitempty"`
	WarnValue  int32  `protobuf:"varint,3,opt,name=warn_value,json=warnValue" json:"warn_value,omitempty"`
	CritValue  int32  `protobuf:"varint,4,opt,name=crit_value,json=critValue" json:"crit_value,omitempty"`
	WarnOutput string `protobuf:"bytes,5,opt,name=warn_output,json=warnOutput" json:"warn_output,omitempty"`
	CritOutput string `protobuf:"bytes,6,opt,name=crit_output,json=critOutput" json:"crit_output,omitempty"`
	Duration   int32  `protobuf:"varint,7,opt,name=duration" json:"duration,omitempty"`
	Template   string `protobuf:"bytes,8,opt,name=template" json:"template,omitempty"`
}

func (m *Alert) Reset()                    { *m = Alert{} }
func (m *Alert) String() string            { return proto1.CompactTextString(m) }
func (*Alert) ProtoMessage()               {}
func (*Alert) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type User struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Sms         string `protobuf:"bytes,2,opt,name=sms" json:"sms,omitempty"`
	Mail        string `protobuf:"bytes,3,opt,name=mail" json:"mail,omitempty"`
	MessagePush string `protobuf:"bytes,4,opt,name=message_push,json=messagePush" json:"message_push,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto1.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto1.RegisterType((*Group)(nil), "proto.Group")
	proto1.RegisterType((*Users)(nil), "proto.Users")
	proto1.RegisterType((*Alerts)(nil), "proto.Alerts")
	proto1.RegisterType((*Reply)(nil), "proto.Reply")
	proto1.RegisterType((*Alert)(nil), "proto.Alert")
	proto1.RegisterType((*User)(nil), "proto.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Alarm service

type AlarmClient interface {
	AddGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Reply, error)
	AddUsers(ctx context.Context, in *Users, opts ...grpc.CallOption) (*Reply, error)
	AddAlerts(ctx context.Context, in *Alerts, opts ...grpc.CallOption) (*Reply, error)
}

type alarmClient struct {
	cc *grpc.ClientConn
}

func NewAlarmClient(cc *grpc.ClientConn) AlarmClient {
	return &alarmClient{cc}
}

func (c *alarmClient) AddGroup(ctx context.Context, in *Group, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/proto.Alarm/AddGroup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) AddUsers(ctx context.Context, in *Users, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/proto.Alarm/AddUsers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alarmClient) AddAlerts(ctx context.Context, in *Alerts, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/proto.Alarm/AddAlerts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Alarm service

type AlarmServer interface {
	AddGroup(context.Context, *Group) (*Reply, error)
	AddUsers(context.Context, *Users) (*Reply, error)
	AddAlerts(context.Context, *Alerts) (*Reply, error)
}

func RegisterAlarmServer(s *grpc.Server, srv AlarmServer) {
	s.RegisterService(&_Alarm_serviceDesc, srv)
}

func _Alarm_AddGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Group)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).AddGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Alarm/AddGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).AddGroup(ctx, req.(*Group))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_AddUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Users)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).AddUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Alarm/AddUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).AddUsers(ctx, req.(*Users))
	}
	return interceptor(ctx, in, info, handler)
}

func _Alarm_AddAlerts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Alerts)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlarmServer).AddAlerts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Alarm/AddAlerts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlarmServer).AddAlerts(ctx, req.(*Alerts))
	}
	return interceptor(ctx, in, info, handler)
}

var _Alarm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Alarm",
	HandlerType: (*AlarmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddGroup",
			Handler:    _Alarm_AddGroup_Handler,
		},
		{
			MethodName: "AddUsers",
			Handler:    _Alarm_AddUsers_Handler,
		},
		{
			MethodName: "AddAlerts",
			Handler:    _Alarm_AddAlerts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("vgo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 481 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0x26, 0x69, 0xdd, 0x4d, 0x26, 0x05, 0x21, 0x5f, 0x48, 0x23, 0x21, 0xba, 0x39, 0x55, 0x48,
	0x54, 0x50, 0x2e, 0x88, 0x5b, 0x0f, 0xab, 0x15, 0x27, 0x90, 0x25, 0xb8, 0x56, 0x66, 0x63, 0x65,
	0x23, 0x92, 0x26, 0xb2, 0x9d, 0x45, 0x7d, 0x02, 0x78, 0x04, 0x6e, 0x3c, 0x22, 0xaf, 0x80, 0x66,
	0xec, 0x76, 0xd3, 0xa5, 0xe2, 0xd4, 0x53, 0x67, 0xe6, 0xfb, 0xe9, 0xfc, 0x38, 0x10, 0xdf, 0x95,
	0xed, 0xb2, 0xd3, 0xad, 0x6d, 0x39, 0xa3, 0x9f, 0xfc, 0x67, 0x08, 0xec, 0x5a, 0xb7, 0x7d, 0xc7,
	0x9f, 0x40, 0x58, 0x15, 0x69, 0x30, 0x0f, 0x16, 0xb1, 0x08, 0xab, 0x82, 0xbf, 0x86, 0x89, 0xac,
	0x95, 0xb6, 0x26, 0x0d, 0xe7, 0xa3, 0x45, 0xb2, 0x4a, 0x9d, 0x70, 0x49, 0xec, 0xe5, 0x9a, 0xa0,
	0xab, 0xad, 0xd5, 0x3b, 0xe1, 0x79, 0xfc, 0x15, 0xb0, 0xde, 0x28, 0x6d, 0xd2, 0x11, 0x09, 0x9e,
	0x1d, 0x09, 0x3e, 0x23, 0xe2, 0xf8, 0x8e, 0x95, 0x5d, 0x43, 0x32, 0x70, 0xe1, 0x4f, 0x61, 0xf4,
	0x4d, 0xed, 0x7c, 0x03, 0x18, 0xf2, 0x1c, 0xd8, 0x9d, 0xac, 0x7b, 0x95, 0x86, 0xf3, 0x60, 0x91,
	0xac, 0xa6, 0xde, 0x8f, 0x44, 0xc2, 0x41, 0xef, 0xc3, 0x77, 0x41, 0x76, 0x05, 0x70, 0xef, 0x7e,
	0xc2, 0xe7, 0xf2, 0xd8, 0x27, 0xf1, 0x3e, 0xa8, 0x19, 0xd8, 0xe4, 0xbf, 0x02, 0x60, 0xe4, 0xc3,
	0x67, 0x10, 0x95, 0xd8, 0xf4, 0xe6, 0xb0, 0x90, 0x0b, 0xca, 0x3f, 0x14, 0xf7, 0x33, 0x86, 0x47,
	0x33, 0x92, 0xee, 0xc4, 0x8c, 0x67, 0x6a, 0xed, 0x77, 0x00, 0x13, 0xb7, 0xab, 0xff, 0xf5, 0xf6,
	0xe6, 0xc1, 0xc5, 0x66, 0xc3, 0x85, 0x99, 0x53, 0x27, 0x3b, 0xdb, 0x0d, 0xf2, 0x19, 0x30, 0xa1,
	0xba, 0x9a, 0x2c, 0x1a, 0x53, 0xee, 0x2d, 0x1a, 0x53, 0xe6, 0x7f, 0x02, 0x60, 0xc4, 0xe7, 0x1c,
	0xc6, 0x76, 0xd7, 0x29, 0x02, 0x99, 0xa0, 0x98, 0x67, 0x10, 0xb5, 0x9d, 0xd2, 0xd2, 0xb6, 0x9a,
	0xfe, 0x83, 0x89, 0x43, 0xce, 0x9f, 0x03, 0x7c, 0x97, 0x7a, 0xbb, 0x71, 0x1d, 0x8c, 0x08, 0x8d,
	0xb1, 0xf2, 0x05, 0x0b, 0x08, 0xdf, 0xe8, 0xca, 0x7a, 0x78, 0xec, 0x60, 0xac, 0x38, 0xf8, 0x05,
	0x24, 0xa4, 0x6e, 0x7b, 0xdb, 0xf5, 0x36, 0x65, 0xd4, 0x11, 0x19, 0x7e, 0xa4, 0x0a, 0x12, 0x48,
	0xef, 0x09, 0x13, 0x47, 0xc0, 0x92, 0x27, 0x64, 0x10, 0x15, 0xbd, 0x96, 0xb6, 0x6a, 0xb7, 0xe9,
	0x85, 0xeb, 0x6d, 0x9f, 0x23, 0x66, 0x55, 0xd3, 0xd5, 0xd2, 0xaa, 0x34, 0x22, 0xe5, 0x21, 0xcf,
	0x6f, 0x60, 0x8c, 0x17, 0xc4, 0x79, 0xb7, 0xb2, 0x51, 0x7e, 0x19, 0x14, 0xe3, 0x7e, 0x4c, 0x63,
	0x68, 0xd4, 0x58, 0x60, 0x88, 0xac, 0x46, 0x56, 0x35, 0xcd, 0x17, 0x0b, 0x8a, 0xf9, 0x25, 0x4c,
	0x1b, 0x65, 0x8c, 0x2c, 0xd5, 0xa6, 0xeb, 0xcd, 0x2d, 0x0d, 0x17, 0x8b, 0xc4, 0xd7, 0x3e, 0xf5,
	0xe6, 0x76, 0xf5, 0x83, 0xd6, 0x2a, 0x75, 0xc3, 0x17, 0x10, 0xad, 0x8b, 0xc2, 0x7d, 0xc5, 0xd3,
	0xe1, 0x47, 0x97, 0xed, 0x33, 0x3a, 0x4d, 0xfe, 0xc8, 0x33, 0xdd, 0x23, 0x9f, 0x0e, 0x9f, 0xee,
	0x3f, 0xcc, 0x97, 0x10, 0xaf, 0x8b, 0xc2, 0xbf, 0xb9, 0xc7, 0x47, 0x0f, 0xe9, 0x21, 0xf7, 0xeb,
	0x84, 0xd2, 0xb7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x8a, 0x3d, 0xc1, 0x5e, 0x04, 0x00,
	0x00,
}
